# Generated by Django 3.0 on 2020-03-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_nutrifile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrifile',
            name='calories',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nutrifile',
            name='carbohydrates',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nutrifile',
            name='cholestrol',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nutrifile',
            name='fiber',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nutrifile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutrifile',
            name='protein',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nutrifile',
            name='serving_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nutrifile',
            name='total_fat',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
