# Generated by Django 3.0 on 2020-04-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20200322_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrifile',
            name='detail',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='nutrifile',
            name='calories',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='nutrifile',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='nutrifile',
            name='cholestrol',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='nutrifile',
            name='fiber',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='nutrifile',
            name='protein',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='nutrifile',
            name='serving_size',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='nutrifile',
            name='total_fat',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
